deviantfero/wpgtk

- README.md
pip ==> python-pip
also pulls in all the dependencies needed related to python imaging
and 4 other libraries needed
> Fixed Ubuntu dependency errors

- themes/flattrcolor/index.theme
This will allow user to identify which on is the wpgtk version if regular Flattr is installed as well.
> Set FlattrColor icon set name to "FlattrColor"

- wpg
Since ```-V``` is only ever used with ```-t```, I would recommend to assume ```-t``` every time ```-V``` is set.
> Run --vte even without --tty

- wpgtk/data/sample.py
`pywal` exposes some color manipulating functions through the `util` module. 
Code from `pywal`:
```py
def hex_to_rgb(color):
"""Convert a hex color to rgb.""" 
return tuple(bytes.fromhex(color.strip("#")))
```
> sample.py: Use 'pywal' function instead.

- setup.py
- wpgtk/__init__.py
- wpgtk/data/config.py
This makes it easier to create new releases since there's only one number to increment. 
- Removes unused `shutil` import from `setup.py`.
- Exposes `__version__` to `setup.py`.
> setup.py: Don't hardcode version number.

- wpgtk/data/config.py
Fixes startup problems when wpgtk is installed in none default site-packages path (e.g. with ```pip -user```).
This should fix #54.
> Copy config bakup from install path

- wpgtk/data/config.py
This simplifies one of the recent commits. 
- `__file__` stores the path to the `config.py` file. 
- We then go up **two** directories to `wpgtk/wpgtk` to get the module path.
- We then join the module path with the config path.
- This also exposes `MODULE_DIR` so you can re-use it later in the script if needed.
(You can also remove the fallback to `/usr/local` since it won't be used anymore(?))
> config.py: Simplify config handling.

- README.md
- wpgtk/__main__.py
- wpgtk/data/color.py
- wpgtk/data/config.py
- wpgtk/data/files.py
- wpgtk/data/themer.py
- wpgtk/gui/color_grid.py
- wpgtk/gui/option_grid.py
- wpgtk/gui/template_grid.py
- wpgtk/gui/theme_picker.py
- wpgtk/misc/wpg-install.sh
I need to clear confusion on how this system works, it is a simple way to add support for any software to have it's own template and it's own colors changed each time `wpgtk` changes the colorscheme, for this reason I feel it should be the main focus of the proyect, `GTK`, `tint2` and `openbox` are just special cases of these templates. In order to do so, I plan to clear up some things:
> Improving custom template system (previously Optional files)

- wpgtk/data/color.py
- wpgtk/data/config.py
- wpgtk/data/util.py
- wpgtk/misc/wpg-install.sh
Previously overlapping keywords would conflict, an example of this below:
```
KEYWORD1  -> firstvalue
KEYWORD11 -> firstvalue1
```
resulting in corrupted configuration files unless the keywords were completely different from one another, for this reason I've introduced this new syntax for keywords on template files, this is the same example above with the new syntax.
```
<KEYWORD1>  -> firstvalue
<KEYWORD11> -> differentvalue
```
This resolves the issue and allows for any keyword, wether it's overlaping or not, to be available to the user, this also means that `wpgtk` own color keywords can be simpler, and they're now defined as follows.
```
COLOR1   becomes <COLOR1>
COLORX10 becomes <COLOR10>
COLORACT becomes <COLORACT>
COLORIN  becomes <COLORIN>
```
So we have our 15 colors in …
> change new keyword syntax to avoid conflicts in overlapping keyword

- README.md
- completions/bash/wpg
- completions/zsh/_wpg
- wpgtk/__main__.py
- wpgtk/data/color.py
- wpgtk/data/config.py
- wpgtk/data/sample.py
- wpgtk/data/themer.py
- wpgtk/data/util.py
- wpgtk/gui/color_grid.py
- wpgtk/gui/color_picker.py
- wpgtk/gui/keyword_grid.py
- wpgtk/gui/option_grid.py
- wpgtk/gui/template_grid.py
- wpgtk/gui/theme_picker.py
- wpgtk/misc/wpg.conf
In this release I will add support for the many themes @dylanaraps has added to [pywal](https://github.com/dylanaraps/pywal), with the same ability to edit this themes and save them at your leisure that `wpgtk` posseses.
here's a checklist of goals for this release:
> pywal themes support

- wpgtk/__main__.py
- wpgtk/data/color.py
- wpgtk/data/config.py
- wpgtk/data/files.py
- wpgtk/data/keywords.py
- wpgtk/data/sample.py
- wpgtk/data/themer.py
- wpgtk/gui/color_grid.py
- wpgtk/gui/keyword_grid.py
- wpgtk/gui/option_grid.py
- wpgtk/gui/template_grid.py
- wpgtk/gui/theme_picker.py
- wpgtk/misc/wpg-install.sh
- wpgtk/misc/wpg.conf
This PR started as a solution to: https://github.com/deviantfero/wpgtk/issues/99, in which users need to have a set place for each color, that is to say, green always go where green goes, yellow where yellow goes and so on, this is done according to the standard terminal colors order, which is the following:
`black, red, green, yellow, blue, magenta, cyan, white`
when you use the `auto-adjust` functions, the colors will also be sorted in this fashion, if you want to disable this functionality you can do so via the `smart_sort` setting in the configuration file, you can also disable that from the GUI.
**Other changes include:**
* Folder structure changed
```sh
.config/wpg
├── formats
├── samples
├── schemes
├── sequences
├── templates
├── wallpapers
├── wpg.conf
└── wp_init.sh
```
* in …
> smart color sorting - v5.7.0 inbound, read more

- setup.py
Changes how wpgtk checks the current running Python version in setup.py to use `sys.version_info` rather than doing a try/except wrapped around importing the main module.
> Change how wpgtk checks version in setup.py

- wpgtk/data/themer.py
By changing the shebang, the script searches in the `$PATH` for bash, instead of assuming that bash is located at `/bin/`.
This change is necessary for Distributions like NixOS which store the binaries at another location.
> change shebang to /bin/env bash

- completions/bash/wpg
- completions/zsh/_wpg
- setup.py
- wpgtk/__main__.py
- wpgtk/data/color.py
- wpgtk/data/config.py
- wpgtk/data/files.py
- wpgtk/data/reload.py
- wpgtk/data/themer.py
- wpgtk/data/util.py
- wpgtk/gui/color_grid.py
- wpgtk/gui/option_grid.py
- wpgtk/misc/wpg-install.sh
- wpgtk/misc/wpg.conf
I will be changing up a few things around, there are some breaking changes, so I think this is indeed worthy of a major version release, here's a checklist of things that I'm working on:
Basically, the breaking changes come from the fact that the template format will change, I provide an example below:
```
#<COLOR8> becomes {color8}
#<COLORACT> becomes {active}
#<COLORIN> becomes {inactive}
if you have normal braces {{
you will need to escape them like this
}}
but this means you can do things like: 
{color8}                -> #ffffff
{color8.octal}          -> #77777777
{active.rgb}            -> 255, 255, 255
{userdefinedcolor.rgb}  -> 0, 0, 0
#BA{color8.strip}       -> #BAffffff
```
> New template format

- wpgtk/data/themer.py
In the original commit, reload.xrdb() was supposed to be moved to be run before anything else. I'm not sure where it was supposed to be moved, but it got removed entirely, breaking wp_init.sh. I have added it back and now my terminal colors save upon reboot.
> Added reload.xrdb() back

- setup.py
- wpgtk/data/config.py
- wpgtk/misc/wpg-install.sh
See https://wiki.archlinux.org/index.php/XDG_Base_Directory.
pywal does it, and it's a pretty straightforward change.
Moving the icon/theme directories didn't give me any problems when I tested, since it looks like GTK looks under both ~/.{icons,themes} and XDG_DATA_HOME/{icons,themes}. So this should be backwards compatible.
> Use XDG directories

- README.md
Possessive of "it" is written as "its" and not "it's" (http://its-not-its.info/)
Third person usage of "let" is written as "lets". "Let's" is short for "let us".
Also thank you for this amazing program. Just what I was looking for, for the last few months.
> Minor grammar edits

- wpgtk/__main__.py
- wpgtk/data/themer.py
- wpgtk/gui/option_grid.py
- wpgtk/misc/wpg.conf
Not sure if this is something youre interested in adding, but Im currently learning how to use wpgtk and this was a feature that I was missing since I like to perform reloads manually afterwards through my own script
Wasnt sure on what help message and gtk label to use, so consider what I have as a temp placeholder and im open to suggestions
thank you
> added option to disable calling themer.py's reload.all()

- wpgtk/__main__.py
- wpgtk/data/themer.py
This allows included light pywal themes to be set using a combination of `-L` and `--theme` flags, for example `wpg -L --theme solarized`.
> Allow included light pywal themes to be set

- wpgtk/data/reload.py
As I said in #112 , the code now expects the user to use Flatcolor theme. And if reload GTK+ is enabled, it sets the theme to Flatcolor without even checking if the theme is installed or not. This makes the GTK live reloading kind of broken.
So I am proposing in this PR to do the following for live refreshing GTK apps.
1. If using gnome-settings-daemon.
- If it is running, then we dont need the optional dependency xsettingsd installed and still can update the theme with just refreshing the gsettings (with the users theme even if Flatcolor is not installed)
2. If their is no settings daemon running:
- This means GTK apps are not getting the themes info from dconf. They may get the theme from `~/.config/gtk-3.0/settings.ini` as said in case of lxappearance or other GTK theme managers.
- So …
> Made the live gtk reload more robust.

- wpgtk/misc/wpg-install.sh
When you run `wpg-install -gi` without a `.themes` directory in your home dir the GTK2 theme installation fails
```
Installing gtk themes
ln: failed to create symbolic link '/home/username/.themes/FlatColor': No such file or directory
:: gtk3.0 theme done
:: gtk3.20 theme done
:: FlatColor gtk themes install done.
Installing icon pack
:: flattr icons install done.
```
Running `mkdir -p .themes` fixes this issue.
> Create THEMES_DIR if it doesn't exist yet

- wpgtk/data/reload.py
You may have forgot to format and insert the theme name in case of xfce theme gtk reloading. Fixed it.
> Fixed gtk reloading in xfsettings command formatting.

- wpgtk/misc/wpg-install.sh
Basic QTile color support. Adds an import to the color list inside user's config. Users do have to change their configs once to put the color references in place. While I have tested the script on my own machine a few times, I am nowhere near proficient in bash, so please do double check it just in case.
> Added QTile support

- wpgtk/__main__.py
- wpgtk/data/color.py
- wpgtk/data/config.py
- wpgtk/data/files.py
- wpgtk/data/keywords.py
- wpgtk/data/reload.py
- wpgtk/data/sample.py
- wpgtk/data/themer.py
- wpgtk/gui/color_grid.py
- wpgtk/gui/keyword_dialog.py
- wpgtk/gui/keyword_grid.py
- wpgtk/gui/option_grid.py
- wpgtk/gui/template_grid.py
- wpgtk/gui/theme_picker.py
> Implement keyword per colorscheme feature/interface

- wpgtk/data/reload.py
Fixes #158 .
Since it seems you are busy, I have fixed the dunst reload issue. I have been using this version on Arch for a long time now without any problems.
This does mean that any dunst instances running from a custom configuration file will not be reloaded properly. Until the dunst maintainers add the option to send a signal to reload, this is the best we can do.
> Restart dunst on reload.

- wpgtk/data/reload.py
Fix bug where Settings section exist, but the gtk-theme-name key does not exist not exist. 
In this edge case theme is set to `None`, which when passed to `xsettingsd()` errors out with a `TypeError` since you cannot concatenate string with NoneType (line 53)
Sample error message:
```
✖ cat ~/.config/gtk-3.0/settings.ini 
[Settings]
gtk-application-prefer-dark-theme=0
➜ wpg -s 4color-kasumi.jpg                  [i] image         Using image 4color-kasumi.jpg.
[i] theme         Set theme to _home_zegheim__config_wpg_wallpapers_4color-kasumi_jpg_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] sequences     Set terminal colors.
[i] export        Exported all files.
[i] export        Exported all user files.
[i] color         wrote: icon-step1
[i] color         wrote: …
```
> Fix bug where Settings section exist, but the gtk-theme-name key does not exist

- wpgtk/gui/theme_picker.py
* wpgtk crashes on launch after having selected a gif as a wallpaper.
* wpgtk does not update the wallpaper preview properly if it is a gif (happens if you launch it with a normal wallpaper selected and then try to select a gif wallpaper).
```
[i] theme_picker  current wallpaper: GiantSkeletonCleanSpriting2_small.gif
Traceback (most recent call last):
File "/usr/bin/wpg", line 33, in <module>
sys.exit(load_entry_point('wpgtk==6.5.5', 'console_scripts', 'wpg')())
File "/usr/lib/python3.10/site-packages/wpgtk/__main__.py", line 309, in main
_gui.run(args)
File "/usr/lib/python3.10/site-packages/wpgtk/gui/theme_picker.py", line 196, in run
win = mainWindow(args)
File "/usr/lib/python3.10/site-packages/wpgtk/gui/theme_picker.py", line 82, in __init__
self.pixbuf_preview = …
```
> fix crash when dealing with gif wallpapers

- wpgtk/data/files.py
- wpgtk/data/util.py
The previous method of comparing versions is bad. It is not able to work in borderline cases, for example, with version 10.1.2, 1 will be compared with 3, 0 with 3 and 1 with 0, because there is iteration over symbols without concatenation...
A new function has also been added to util.py, i think it can be useful in many places in app.
Also fixed version comparison in the __check_is_pywal16cols, because in previous impl it can return True if smth like 2.4.3 used.
Sorry for this mistakes, i screwed up a little.
> Avoid future errors and refactor
